rem reference from https://hituji-ws.com/code/python/python-emb-usage/
SET TARGET_ROOT=%~1
IF "%TARGET_ROOT%"=="" SET TARGET_ROOT=%~dp0
IF "%TARGET_ROOT:~-1%"=="\" SET TARGET_ROOT=%TARGET_ROOT:~0,-1%

SET DP0=%TARGET_ROOT%
SET SHARED_DIR=%~dp0
SET SHARED_DIR=%SHARED_DIR:~0,-1%

rem overriding windows user/local environment
SET LOCALENV_DIR=%DP0%\_local_env
SET TMP=%LOCALENV_DIR%\_tmp
SET TEMP=%LOCALENV_DIR%\_tmp
SET HOME=%LOCALENV_DIR%\userprofile
SET HOMEPATH=%LOCALENV_DIR%\userprofile
SET LOCALAPPDATA=%LOCALENV_DIR%\localappdata
SET APPDATA=%LOCALENV_DIR%\userroaming
SET LABELMAKR_HF_CACHE_DIR=%DP0%\.cache\huggingface
SET HF_HOME=%LABELMAKR_HF_CACHE_DIR%
SET HUGGINGFACE_HUB_CACHE=%LABELMAKR_HF_CACHE_DIR%\hub
IF NOT EXIST "%LABELMAKR_HF_CACHE_DIR%" MKDIR "%LABELMAKR_HF_CACHE_DIR%"
IF NOT EXIST "%HUGGINGFACE_HUB_CACHE%" MKDIR "%HUGGINGFACE_HUB_CACHE%"

SET PYTHON_PATH=%DP0%\python

rem overriding default python env vars in order to interfere with any system python installation
SET PYTHONHOME=
SET PYTHONPATH=
SET PYTHONEXECUTABLE=%PYTHON_PATH%\python.exe
SET PYTHONWEXECUTABLE=%PYTHON_PATH%\pythonw.exe

SET PYTHON_EXECUTABLE=%PYTHON_PATH%\python.exe
SET PYTHONW_EXECUTABLE=%PYTHON_PATH%\pythonw.exe
SET PYTHON_BIN_PATH=%PYTHON_EXECUTABLE%
SET PYTHON_LIB_PATH=%PYTHON_PATH%\Lib\site-packages
SET TCL_LIBRARY=%PYTHON_PATH%\tcl\tcl8.6
SET TK_LIBRARY=%PYTHON_PATH%\tcl\tk8.6
SET NoDefaultCurrentDirectoryInExePath=1
SET PATH=%DP0%;%PYTHON_PATH%;%PYTHON_PATH%\DLLs;%PYTHON_PATH%\Scripts;%SHARED_DIR%;%DP0%\CMake\Bin;%PATH%
SET DISTUTILS_USE_SDK=1